[[weeks]]
name = "Week 2"

[[weeks.studies]]
weekday = "sunday"
date = "2025-11-16"
attended = [ "662201438621138954", "824524491140628523", "485801939431456799", "413400150094905344", "878092667156856882", "577266050769485844", "261556699431698433", "450594431901368320", "816504505259786270", "1352566338136309822", "937273161324564540", "1102060210899665007", "777100063234588672", "387858780412706817", "718700033993736192", "495046472413216770", "1272478564209393678", "370100048811524099", "844571376501522432", "1412060321031651358", "1397468588658659398", "348349452559319040", "1261379196366880788" ]

[[weeks]]
name = "Week 3"

[[weeks.studies]]
weekday = "saturday"
date = "2025-11-22"
attended = [ "577266050769485844", "718700033993736192", "1102060210899665007", "495046472413216770", "387858780412706817", "988438501974503484", "1352566338136309822", "1261379196366880788", "261556699431698433", "1321366965364723763", "844571376501522432" ]

[[weeks.studies]]
weekday = "sunday"
date = "2025-11-23"
attended = [ "777100063234588672", "844571376501522432", "1397468588658659398", "450594431901368320", "937273161324564540", "602523632358653953", "718700033993736192", "370100048811524099", "816504505259786270", "1006043413008887838", "431794719232753664", "690148325604720660", "577266050769485844", "878092667156856882", "261556699431698433", "824524491140628523", "1321366965364723763", "387858780412706817" ]

[[weeks]]
name = "Week 4"

[[weeks.studies]]
weekday = "saturday"
date = "2025-11-29"
attended = [ "431794719232753664", "387858780412706817", "718700033993736192", "777100063234588672", "1321366965364723763", "1352566338136309822", "816504505259786270", "261556699431698433", "1006043413008887838", "495046472413216770", "602523632358653953", "844571376501522432", "988438501974503484" ]

[[weeks.studies]]
weekday = "sunday"
date = "2025-11-30"
attended = [ "844571376501522432", "602523632358653953", "824524491140628523", "387858780412706817", "450594431901368320", "391627940548575232", "370100048811524099", "816504505259786270", "937273161324564540", "878092667156856882", "718700033993736192", "261556699431698433" ]

[[weeks]]
name = "Week 5"

[[weeks.studies]]
weekday = "saturday"
date = "2025-12-06"
attended = [ "718700033993736192", "431794719232753664", "988438501974503484", "753625063357546556", "387858780412706817", "873247209578176572", "844571376501522432", "495046472413216770", "824524491140628523", "665578605136576512" ]

[[weeks.studies]]
weekday = "sunday"
date = "2025-12-07"
attended = [ "387858780412706817", "988438501974503484", "816504505259786270", "844571376501522432", "602523632358653953", "824524491140628523", "1397468588658659398", "777100063234588672" ]

[[weeks]]
name = "Week 6"

[[weeks.studies]]
weekday = "monday"
date = "2025-12-08"
attended = [ "829684746904403978" ]

[[weeks.studies]]
weekday = "wednesday"
date = "2025-12-10"
attended = [ "391627940548575232" ]

[[weeks]]
name = "Week 7"

[[weeks.studies]]
weekday = "saturday"
date = "2025-12-20"
attended = [ "1006043413008887838", "431794719232753664", "844571376501522432", "718700033993736192", "665578605136576512", "1352566338136309822", "878092667156856882", "387858780412706817", "824524491140628523", "261556699431698433", "753625063357546556", "602523632358653953" ]

[[weeks.studies]]
weekday = "sunday"
date = "2025-12-21"
attended = [ "602523632358653953", "1321366965364723763", "753625063357546556", "387858780412706817", "718700033993736192", "577266050769485844", "878092667156856882" ]
