name = "Rust ì—°ë§ ì˜¨ë¼ì¸ ìŠ¤í„°ë”” ê·¸ë£¹"
start_date = 2025-11-08
end_date = 2026-01-11

[[study_time]]
weekday = "saturday"
start_time = 19:00:00
end_time = 21:00:00

[[study_time]]
weekday = "sunday"
start_time = 20:00:00
end_time = 22:00:00

[channels]
main = "1434997353810759792"
stage = "1434997706673229956"

[lecturer]
nickname = "í•œí˜„ë¹ˆ"
id = "348349452559319040"

[[members]]
nickname = "noobnuby"
id = "878092667156856882"
primary_study_weekday = "saturday"

[[members]]
nickname = "ë„í•œ"
id = "1261379196366880788"
primary_study_weekday = "saturday"

[[members]]
nickname = "ëƒ‰ë¬œ"
id = "602523632358653953"
primary_study_weekday = "saturday"

[[members]]
nickname = "Inter"
id = "261556699431698433"
primary_study_weekday = "sunday"

[[members]]
nickname = "Duelit"
id = "1006043413008887838"
primary_study_weekday = "saturday"

[[members]]
nickname = "tyange"
id = "777100063234588672"
primary_study_weekday = "sunday"

[[members]]
nickname = "nyani ' >')"
id = "1352566338136309822"
primary_study_weekday = "saturday"

[[members]]
nickname = "neco"
id = "431794719232753664"
primary_study_weekday = "saturday"

[[members]]
nickname = "Holiday"
id = "824524491140628523"
primary_study_weekday = "saturday"

[[members]]
nickname = "ë°•êµ¬ë‘"
id = "370100048811524099"
primary_study_weekday = "sunday"

[[members]]
nickname = "ãƒ¦ãƒŸ(ìœ ë¯¸)"
id = "829684746904403978"
primary_study_weekday = "saturday"

[[members]]
nickname = "easteregg423"
id = "495046472413216770"
primary_study_weekday = "saturday"

[[members]]
nickname = "6kitty"
id = "873247209578176572"
primary_study_weekday = "saturday"

[[members]]
nickname = "#[derive(Asta)]"
id = "577266050769485844"
primary_study_weekday = "sunday"

[[members]]
nickname = "ì§‘ê°€ê³ ì‹¶ë‹¤"
id = "937273161324564540"
primary_study_weekday = "sunday"

[[members]]
nickname = "EthanH_"
id = "988438501974503484"
primary_study_weekday = "sunday"

[[members]]
nickname = "ny64"
id = "690148325604720660"
primary_study_weekday = "sunday"

[[members]]
nickname = "(í•‘X) ë…¸ì„ğŸœ²"
id = "387858780412706817"
primary_study_weekday = "saturday"

[[members]]
nickname = "Seol"
id = "763422064794796042"
primary_study_weekday = "sunday"

[[members]]
nickname = "ê³ ë¼ë‹ˆ"
id = "844571376501522432"
primary_study_weekday = "saturday"

[[members]]
nickname = "ì˜¤ë¦°"
id = "718700033993736192"
primary_study_weekday = "saturday"

[[members]]
nickname = "SIMD"
id = "1321366965364723763"
primary_study_weekday = "saturday"

[[members]]
nickname = "ëŠ™ê³ ë³‘ë“¬"
id = "450594431901368320"
primary_study_weekday = "sunday"

[[members]]
nickname = "doc_raid"
id = "391627940548575232"
primary_study_weekday = "sunday"

[[members]]
nickname = "imgcode"
id = "1397468588658659398"
primary_study_weekday = "sunday"

[[members]]
nickname = "OkJa"
id = "1102060210899665007"
primary_study_weekday = "sunday"

[[members]]
nickname = "ì„ê·œì§„"
id = "816504505259786270"
primary_study_weekday = "sunday"

[[members]]
nickname = "Dux0"
id = "1336184122330320987"
primary_study_weekday = "sunday"
